//  _      ____   _____ _____ _   _
// | |    / __ \ / ____|_   _| \ | |
// | |   | |  | | |  __  | | |  \| |
// | |   | |  | | | |_ | | | | . ` |
// | |___| |__| | |__| |_| |_| |\  |
// |______\____/ \_____|_____|_| \_|

### Generate Token
POST http://localhost:8080/dae_project/api/login/token
Content-Type: application/json

{
 "username" : "admin",
 "password" : "admin"
}

> {%
    client.test("GENERATE TOKEN", function() {
        client.global.set("token", response.body.token);
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

### VERIFY TOKEN
GET http://localhost:8080/dae_project/api/login/claims
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("VERIFY TOKEN", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
//   __  __          _   _ _    _ ______      _____ _______ _    _ _____  ______ _____   _____
//  |  \/  |   /\   | \ | | |  | |  ____/\   / ____|__   __| |  | |  __ \|  ____|  __ \ / ____|
//  | \  / |  /  \  |  \| | |  | | |__ /  \ | |       | |  | |  | | |__) | |__  | |__) | (___
//  | |\/| | / /\ \ | . ` | |  | |  __/ /\ \| |       | |  | |  | |  _  /|  __| |  _  / \___ \
//  | |  | |/ ____ \| |\  | |__| | | / ____ \ |____   | |  | |__| | | \ \| |____| | \ \ ____) |
//  |_|  |_/_/    \_\_| \_|\____/|_|/_/    \_\_____|  |_|   \____/|_|  \_\______|_|  \_\_____/

###
GET http://localhost:8080/dae_project/api/manufacturers
Accept: application/json

> {%
    client.test("GET ALL MANUFACTURERS", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
GET http://localhost:8080/dae_project/api/manufacturers/fernando78
Accept: application/json

> {%
    client.test("GET ONE MANUFACTURER", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
POST http://localhost:8080/dae_project/api/manufacturers
Content-Type: application/json

{
    "address": "Largo São. Tomé, 25, Bl. 2 8035-007 Gouveia",
    "contact": "936112835",
    "email": "leandro21@hotmail.com",
    "name": "Diana Eva de Rocha",
    "password": "p0DPu0B5Z5",
    "username": "bgoncalves",
    "website": "http://diana.pt"
}
> {%
    client.test("CREATE MANUFACTURER", function() {
        client.assert(response.status === 201, "Response status is " + response.status + " (EXPECTED: 201)");
    });
%}

###
PUT http://localhost:8080/dae_project/api/manufacturers/bgoncalves
Content-Type: application/json

{
  "address": "Largo São. Tomé, 25, Bl. 2 8035-007 Gouveiaaaa",
  "contact": "912345678",
  "email": "leandro21@hotmail.com",
  "name": "Diana Rocha",
  "password": "p0DPu0B5Z5",
  "website": "http://diana-rocha.pt"
}
> {%
    client.test("UPDATE MANUFACTURER", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
DELETE http://localhost:8080/dae_project/api/manufacturers/bgoncalves
Content-Type: application/json

> {%
    client.test("DELETE MANUFACTURER", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}


###
GET http://localhost:8080/dae_project/api/manufacturers/structures
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("GET STRUCTURES WITH MANUFACTURER MATERIALS", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
//            _____  __  __ _____ _   _  _____
//      /\   |  __ \|  \/  |_   _| \ | |/ ____|
//     /  \  | |  | | \  / | | | |  \| | (___
//    / /\ \ | |  | | |\/| | | | | . ` |\___ \
//   / ____ \| |__| | |  | |_| |_| |\  |____) |
//  /_/    \_\_____/|_|  |_|_____|_| \_|_____/

###
GET http://localhost:8080/dae_project/api/admins
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("GET ALL ADMINS", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
GET http://localhost:8080/dae_project/api/admins/admin
Accept: application/json

> {%
    client.test("GET ONE ADMIN", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
POST http://localhost:8080/dae_project/api/admins
Content-Type: application/json

{
  "username": "eu",
  "password": "eu",
  "email": "eu@eu.com",
  "name": "Eu"
}
> {%
    client.test("CREATE ADMIN", function() {
        client.assert(response.status === 201, "Response status is " + response.status + " (EXPECTED: 201)");
    });
%}

###
PUT http://localhost:8080/dae_project/api/admins/eu
Content-Type: application/json

{
  "password": "eu2",
  "email": "eu@eu.com",
  "name": "Eu"
}
> {%
    client.test("UPDATE ADMIN", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
DELETE http://localhost:8080/dae_project/api/admins/eu
Content-Type: application/json

> {%
    client.test("DELETE ADMIN", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
//    _____ _      _____ ______ _   _ _______ _____
//   / ____| |    |_   _|  ____| \ | |__   __/ ____|
//  | |    | |      | | | |__  |  \| |  | | | (___
//  | |    | |      | | |  __| | . ` |  | |  \___ \
//  | |____| |____ _| |_| |____| |\  |  | |  ____) |
//   \_____|______|_____|______|_| \_|  |_| |_____/
###
GET http://localhost:8080/dae_project/api/clients
Accept: application/json

> {%
    client.test("GET ALL CLIENTS", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
GET http://localhost:8080/dae_project/api/clients/client
Authorization: Bearer {{token}}
Accept: application/json

> {%
    client.test("GET ONE CLIENT", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
POST http://localhost:8080/dae_project/api/clients
Content-Type: application/json

{
  "username": "eu",
  "password": "eu",
  "email": "eu@eu.com",
  "name": "Eu",
  "contact": "fdgdf",
  "address": "sdfde"
}
> {%
    client.test("CREATE CLIENT", function() {
        client.assert(response.status === 201, "Response status is " + response.status + " (EXPECTED: 201)");
    });
%}

###
PUT http://localhost:8080/dae_project/api/clients/eu
Content-Type: application/json

{
  "password": "eu2",
  "email": "eu@eu.com",
  "name": "Eu",
  "contact": "fdgdf",
  "address": "sdfde"
}
> {%
    client.test("UPDATE CLIENT", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
DELETE http://localhost:8080/dae_project/api/clients/eu
Content-Type: application/json

> {%
    client.test("DELETE CLIENT", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
//   _____  ______  _____ _____ _____ _   _ ______ _____   _____
//  |  __ \|  ____|/ ____|_   _/ ____| \ | |  ____|  __ \ / ____|
//  | |  | | |__  | (___   | || |  __|  \| | |__  | |__) | (___
//  | |  | |  __|  \___ \  | || | |_ | . ` |  __| |  _  / \___ \
//  | |__| | |____ ____) |_| || |__| | |\  | |____| | \ \ ____) |
//  |_____/|______|_____/|_____\_____|_| \_|______|_|  \_\_____/


//   _____  _____   ____       _ ______ _____ _______ _____
//  |  __ \|  __ \ / __ \     | |  ____/ ____|__   __/ ____|
//  | |__) | |__) | |  | |    | | |__ | |       | | | (___
//  |  ___/|  _  /| |  | |_   | |  __|| |       | |  \___ \
//  | |    | | \ \| |__| | |__| | |___| |____   | |  ____) |
//  |_|    |_|  \_\\____/ \____/|______\_____|  |_| |_____/


//   ______      __  __ _____ _      _____ ______  _____
//  |  ____/\   |  \/  |_   _| |    |_   _|  ____|/ ____|
//  | |__ /  \  | \  / | | | | |      | | | |__  | (___
//  |  __/ /\ \ | |\/| | | | | |      | | |  __|  \___ \
//  | | / ____ \| |  | |_| |_| |____ _| |_| |____ ____) |
//  |_|/_/    \_\_|  |_|_____|______|_____|______|_____/

###
GET http://localhost:8080/dae_project/api/families
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("GET ALL FAMILIES", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
GET http://localhost:8080/dae_project/api/families/1
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("GET ONE FAMILY", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
POST http://localhost:8080/dae_project/api/families
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "manufacturerUsername": "manu",
  "name": "Section AB"
}
> {%
    client.test("CREATE FAMILY", function() {
        client.assert(response.status === 201, "Response status is " + response.status + " (EXPECTED: 201)");
    });
%}

###
PUT http://localhost:8080/dae_project/api/families/162
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "SECTION ABC"
}
> {%
    client.test("UPDATE FAMILY", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
DELETE http://localhost:8080/dae_project/api/families/162
Content-Type: application/json
Authorization: Bearer {{token}}

> {%
    client.test("DELETE FAMILY", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

###
//   __  __       _______ ______ _____  _____          _       _____
//  |  \/  |   /\|__   __|  ____|  __ \|_   _|   /\   | |     / ____|
//  | \  / |  /  \  | |  | |__  | |__) | | |    /  \  | |    | (___
//  | |\/| | / /\ \ | |  |  __| |  _  /  | |   / /\ \ | |     \___ \
//  | |  | |/ ____ \| |  | |____| | \ \ _| |_ / ____ \| |____ ____) |
//  |_|  |_/_/    \_\_|  |______|_|  \_\_____/_/    \_\______|_____/

### Get Materials
GET http://localhost:8080/dae_project/api/materials/
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("GET ALL MATERIALS", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

### Get 1 Material
GET http://localhost:8080/dae_project/api/materials/1
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test("GET ONE MATERIAL", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

### Create Profile
POST http://localhost:8080/dae_project/api/materials/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "familyID": 1,
  "manufacturerUsername": "manu",
  "name": "C 120/50/21 x 1.123123",
  "profile": {
    "ar": 375.0,
    "sigmaC": 220000.0,
    "weff_n": 13846.0,
    "weff_p": 13846.0,
    "mcr_n": {"entry": []},
    "mcr_p": {
      "entry": [
        {"key": 3.0,"value": 243.2123113},
        {"key": 4.0,"value": 145.238784},
        {"key": 5.0,"value": 99.15039028},
        {"key": 6.0,"value": 73.71351699},
        {"key": 7.0,"value": 58.07716688},
        {"key": 8.0,"value": 47.68885195},
        {"key": 9.0,"value": 40.37070843},
        {"key": 10.0,"value": 34.9747033},
        {"key": 11.0,"value": 30.84866055},
        {"key": 12.0,"value": 27.59984422}
      ]
    }
  }
}
> {%
    client.test("CREATE PROFILE", function() {
        client.assert(response.status === 201, "Response status is " + response.status + " (EXPECTED: 201)");
    });
%}

### Create Sheet
POST http://localhost:8080/dae_project/api/materials/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "familyID": 1,
  "manufacturerUsername": "manu",
  "name": "C 120/50/21 x 1.123123",
  "sheet": {
    "thickness": 0.6
  }
}
> {%
    client.test("CREATE SHEET", function() {
        client.assert(response.status === 201, "Response status is " + response.status + " (EXPECTED: 201)");
    });
%}

### Update Profile
PUT http://localhost:8080/dae_project/api/materials/8
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "familyID": 1,
  "name": "C 120/50/21 x 1",
  "profile": {
    "ar": 375.0,
    "sigmaC": 220000.0,
    "weff_n": 13846.0,
    "weff_p": 13846.0,
    "mcr_n": {"entry": []},
    "mcr_p": {
      "entry": [
        {"key": 3.0,"value": 243.2123113},
        {"key": 4.0,"value": 145.238784},
        {"key": 5.0,"value": 99.15039028},
        {"key": 6.0,"value": 73.71351699},
        {"key": 7.0,"value": 58.07716688},
        {"key": 8.0,"value": 47.68885195},
        {"key": 9.0,"value": 40.37070843},
        {"key": 10.0,"value": 34.9747033},
        {"key": 11.0,"value": 30.84866055},
        {"key": 12.0,"value": 27.59984422}
      ]
    }
  }
}
> {%
    client.test("UPDATE PROFILE", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}

### Update Sheet
PUT http://localhost:8080/dae_project/api/materials/9
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "familyID": 1,
  "name": "C 120/50/21 x 5",
  "sheet": {
    "thickness": 0.6
  }
}
> {%
    client.test("UPDATE SHEET", function() {
        client.assert(response.status === 200, "Response status is " + response.status + " (EXPECTED: 200)");
    });
%}


###
//   _____  _____   ____  ______ _____ _      ______  _____
//  |  __ \|  __ \ / __ \|  ____|_   _| |    |  ____|/ ____|
//  | |__) | |__) | |  | | |__    | | | |    | |__  | (___
//  |  ___/|  _  /| |  | |  __|   | | | |    |  __|  \___ \
//  | |    | | \ \| |__| | |     _| |_| |____| |____ ____) |
//  |_|    |_|  \_\\____/|_|    |_____|______|______|_____/



###
//    _____ _    _ ______ ______ _______ _____
//   / ____| |  | |  ____|  ____|__   __/ ____|
//  | (___ | |__| | |__  | |__     | | | (___
//   \___ \|  __  |  __| |  __|    | |  \___ \
//   ____) | |  | | |____| |____   | |  ____) |
//  |_____/|_|  |_|______|______|  |_| |_____/



###
//   _____        _   _ ______ _       _____
//  |  __ \ /\   | \ | |  ____| |     / ____|
//  | |__) /  \  |  \| | |__  | |    | (___
//  |  ___/ /\ \ | . ` |  __| | |     \___ \
//  | |  / ____ \| |\  | |____| |____ ____) |
//  |_| /_/    \_\_| \_|______|______|_____/



###
//    _____ _______ _____  _    _  _____ _______ _    _ _____  ______  _____
//   / ____|__   __|  __ \| |  | |/ ____|__   __| |  | |  __ \|  ____|/ ____|
//  | (___    | |  | |__) | |  | | |       | |  | |  | | |__) | |__  | (___
//   \___ \   | |  |  _  /| |  | | |       | |  | |  | |  _  /|  __|  \___ \
//   ____) |  | |  | | \ \| |__| | |____   | |  | |__| | | \ \| |____ ____) |
//  |_____/   |_|  |_|  \_\\____/ \_____|  |_|   \____/|_|  \_\______|_____/



###
//   _    _ _____  _      ____          _____   _____
//  | |  | |  __ \| |    / __ \   /\   |  __ \ / ____|
//  | |  | | |__) | |   | |  | | /  \  | |  | | (___
//  | |  | |  ___/| |   | |  | |/ /\ \ | |  | |\___ \
//  | |__| | |    | |___| |__| / ____ \| |__| |____) |
//   \____/|_|    |______\____/_/    \_\_____/|_____/
